apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml
